#!/bin/sh
exec /usr/bin/google-chrome-old \
    --no-sandbox \
    --no-default-browser-check \
    --no-first-run \
    --disable-sync \
    --disable-background-networking \
    --disable-background-timer-throttling \
    --disable-backgrounding-occluded-windows \
    --disable-breakpad \
    --disable-client-side-phishing-detection \
    --disable-default-apps \
    --disable-hang-monitor \
    --disable-popup-blocking \
    --disable-prompt-on-repost \
    --disable-renderer-backgrounding \
    --disable-features=TranslateUI,BlinkGenPropertyTrees \
    --enable-features=NetworkService,NetworkServiceInProcess \
    --no-service-autorun \
    --metrics-recording-only \
    --no-report-upload \
    --safebrowsing-disable-auto-update \
    --disable-gpu \
    --disable-software-rasterizer \
    --disable-dev-shm-usage \
    "$@"
