general {
    colors = true
    color_good = "#50fa7b"
    color_degraded = "#f1fa8c"
    color_bad = "#e94560"
    interval = 5
}

order += "cpu_usage"
order += "memory"
order += "tztime local"

cpu_usage {
    format = " CPU %usage "
}

memory {
    format = " MEM %used / %total "
    threshold_degraded = "20%"
    threshold_critical = "10%"
}

tztime local {
    format = " %Y-%m-%d %H:%M:%S "
}
